version: '3'
services:
  db:
    image: postgres:11
    env_file:
      - .env
    volumes:
      - db-content:/var/lib/postgresql/data
    networks:
      - overlay

  django:
    image: epickiwi/bdecesi-django
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    volumes:
      - user-media:/code/user-media
    networks:
      - overlay
    deploy:
      replicas: 2

  proxy:
    image: epickiwi/bdecesi-proxy
    volumes:
      - user-media:/var/media
    depends_on:
      - django
      - db
    networks:
      - overlay
      - traefik-net
    deploy:
      replicas: 2
      labels:
        traefik.enable: "true"
        traefik.http.services.bde-cesi.loadbalancer.server.port: "80"

        traefik.http.routers.bde-cesi.entrypoints: web-secure
        traefik.http.routers.bde-cesi.rule: "Host(`bdecesilyon.fr`)"
        traefik.http.routers.bde-cesi.tls.certresolver: letsencrypt

        traefik.http.routers.bde-cesi-insecure.entrypoints: web
        traefik.http.routers.bde-cesi-insecure.rule: "Host(`bdecesilyon.fr`)"
        traefik.http.routers.bde-cesi-insecure.middlewares: force-https@file

        traefik.http.routers.bde-cesi-insecure-old.entrypoints: web
        traefik.http.routers.bde-cesi-insecure-old.rule: "Host(`bdecesi.epickiwi.fr`)"
        traefik.http.routers.bde-cesi-insecure-old.middlewares: bde-cesi-redirect

        traefik.http.routers.bde-cesi-old.entrypoints: web-secure
        traefik.http.routers.bde-cesi-old.rule: "Host(`bdecesi.epickiwi.fr`)"
        traefik.http.routers.bde-cesi-old.middlewares: bde-cesi-redirect
        traefik.http.routers.bde-cesi-old.tls.certresolver: letsencrypt

        traefik.http.middlewares.bde-cesi-redirect.redirectregex.regex: "^(https?)://bdecesi.epickiwi.fr/(.*)"
        traefik.http.middlewares.bde-cesi-redirect.redirectregex.replacement: "$${1}://bdecesilyon.fr/$${2}"
        traefik.http.middlewares.bde-cesi-redirect.redirectregex.permanent: "true"

volumes:
  user-media:
  db-content:

networks:
  overlay:
  traefik-net:
    external: true