# Generated by Django 3.0 on 2019-12-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text="L'URL à réduire", max_length=1024)),
                ('slug', models.CharField(blank=True, help_text="L'identifiant de l'URL (Généré si laissé vide)", max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date de création du lien')),
            ],
        ),
    ]
