# Generated by Django 3.0.1 on 2020-01-01 15:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc

from users.models import User

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_support_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(unique=False, default=""),
            preserve_default=False
        )
    ]
