# Generated by Django 3.0.1 on 2020-02-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200103_1102'),
        ('users', '0008_auto_20200101_1645'),
    ]

    operations = [
    ]
