# Generated by Django 3.0.7 on 2020-06-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_assign_slugs'),
        ('users', '0010_auto_20200612_2139'),
    ]

    operations = [
    ]
