# Generated by Django 3.0.7 on 2020-06-16 07:12

from django.db import migrations
from users.models import User

def fix_support_members(apps, schema_editor):
	db = schema_editor.connection.alias

	all_users = User.objects.using(db).all()
	for user in all_users:
		if user.support_member not in [None, "bds", "bde"]:
			user.support_member = None;
			user.save()
			print("Fixed user support_member field #{}".format(user.id))

class Migration(migrations.Migration):

	dependencies = [
		('users', '0012_auto_20200616_0851'),
	]

	operations = [
		migrations.RunPython(fix_support_members),
	]
