# Generated by Django 2.2.6 on 2019-11-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0014_auto_20191015_1953'),
        ('commissions', '0010_auto_20190924_1752'),
    ]

    operations = [
    ]
