# Generated by Django 2.2.6 on 2019-11-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0015_commission_is_organization'),
        ('commissions', '0015_merge_20191102_1024'),
    ]

    operations = [
    ]
