# Generated by Django 2.2.6 on 2019-11-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0016_auto_20191107_0923'),
        ('commissions', '0018_merge_20191104_1130'),
    ]

    operations = [
    ]
