# Generated by Django 2.2.6 on 2019-11-08 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0019_merge_20191108_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrecommission',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membrecommission',
            name='role',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
