# Generated by Django 3.0.1 on 2019-12-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0020_auto_20191108_0748'),
        ('commissions', '0021_auto_20191203_1333'),
    ]

    operations = [
    ]
