# Generated by Django 3.0.1 on 2020-01-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0022_merge_20191230_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='sport_related',
            field=models.BooleanField(default=False),
        ),
    ]
