# Generated by Django 3.0.1 on 2020-01-12 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commissions', '0023_tag_sport_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrecommission',
            name='commission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='commissions.Commission'),
        ),
        migrations.AlterField(
            model_name='membrecommission',
            name='identification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sport_related',
            field=models.BooleanField(default=False, help_text='Le tag est en rapport avec du sport, les utilisateurs seront encouragés à adhèrer au BDS'),
        ),
    ]
