# Generated by Django 3.0.3 on 2020-03-02 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commissions', '0024_auto_20200112_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='banner',
            field=models.ImageField(blank=True, help_text="Une grande bannière permettant de donner un look d'enfer à la commission", null=True, upload_to='commission/banners'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date de création de la commission'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='deputy',
            field=models.ForeignKey(blank=True, help_text="L'utilisateur ayant le rôle de suppléant sur cette commission", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commission',
            name='description',
            field=models.TextField(help_text='Une loooongue description de la commission pouvant être formaté en Markdown'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, help_text='Date de dissolution de la commission, quand elle passe en `is_active = False`', null=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='is_active',
            field=models.BooleanField(default=True, help_text="La commissions éfféctue elle des activités en ce moment et son conseil d'administration peut il être contacté ?"),
        ),
        migrations.AlterField(
            model_name='commission',
            name='logo',
            field=models.ImageField(help_text='Le logo de la commission pour lui donner une belle image', upload_to='commission/logos'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='name',
            field=models.CharField(help_text='Displayname de la commission', max_length=30),
        ),
        migrations.AlterField(
            model_name='commission',
            name='president',
            field=models.ForeignKey(help_text="L'utilisateur définis comme président de cette commissions", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commission',
            name='short_description',
            field=models.CharField(help_text='Une (très) courte déscription de la commission qui viens se blottur sou son nom en tant que tagline', max_length=60),
        ),
        migrations.AlterField(
            model_name='commission',
            name='slug',
            field=models.SlugField(blank=True, help_text="Le nom de la commission modifié pour quil puisse être utilisé dans l'URL (généré automatiquement)", unique=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text="L'ensemble des tags de la commission", related_name='tags_commissions', to='commissions.Tag'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='treasurer',
            field=models.ForeignKey(help_text="L'utilisateur déffinis comme trésorier de la commission, il peut être le même que l'utilisateur ayant le rôle de président", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasurer_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, help_text="La bannière de lévénement pour lui donner un look d'enfer. Si elle n'est pas défnini, la bannière de la commission sera utilisée", null=True, upload_to='events/photos'),
        ),
        migrations.AlterField(
            model_name='event',
            name='commission',
            field=models.ForeignKey(help_text="La commission organisatrice de l'événement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='commissions.Commission'),
        ),
        migrations.AlterField(
            model_name='event',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, help_text="La date de création de l'événement sur le site"),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text="Une looogue description de l'événement pouvant être formaté en Markdown"),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date_end',
            field=models.DateTimeField(help_text="La date à laquelle l'événement se termine"),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date_start',
            field=models.DateTimeField(help_text="La date à laquelle l'événement commence"),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text="L'emplacement de l'événement", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text="Dsiplayname de l'événement", max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text="Le nom de l'événement formaté pour être valide dans uen URL (Champ généré automatiquement)", unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text="La date de dernière modification de l'événement"),
        ),
        migrations.AlterField(
            model_name='membrecommission',
            name='commission',
            field=models.ForeignKey(help_text="La commission dans laquelle l'utilisateur a adhèré", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='commissions.Commission'),
        ),
        migrations.AlterField(
            model_name='membrecommission',
            name='identification',
            field=models.ForeignKey(help_text="L'utilisateur ayant demandé cette adhesion", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membrecommission',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, help_text="La date de l'adhésion"),
        ),
        migrations.AlterField(
            model_name='membrecommission',
            name='role',
            field=models.CharField(blank=True, default=None, help_text="Le nom du rôle que l'utilisateur tiens avec cette adhésion. Si le rôle est définis, le membre est noté comme faisant partie du conseil d'administration mais n'as pas de permissions supplémentaires", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Couleur HTML valide du tag dans le site', max_length=20),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Displayname du tag', max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='Le nom du tag modifié pour être utilisé dans une URL (généré automatiquement)', unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sport_related',
            field=models.BooleanField(default=False, help_text='Si tag est en rapport avec du sport, les utilisateurs seront encouragés à adhèrer au BDS'),
        ),
    ]
