# Generated by Django 3.0.1 on 2020-01-12 15:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20200112_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 15, 1, 25, 598782, tzinfo=utc)),
        ),
    ]
