# Generated by Django 3.0.1 on 2020-01-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='filename',
        ),
    ]
