# Generated by Django 3.0.3 on 2020-03-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20191201_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quicklink',
            name='page',
            field=models.CharField(choices=[('index', "Page d'accueil"), ('search', 'Recherche uniquement')], default='index', help_text="Page d'affichage du lien", max_length=50),
        ),
    ]
