# Generated by Django 3.0.3 on 2020-03-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_quicklink_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklink',
            name='description',
            field=models.CharField(blank=True, help_text="Courte description du lien et l'URL qu'il pointe", max_length=255, null=True),
        ),
    ]
